# Generated by Django 3.1.4 on 2020-12-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_cellars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
