# Generated by Django 3.1.4 on 2020-12-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_cellars', '0002_bottle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='appellation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
