# Generated by Django 3.1.4 on 2020-12-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_cellars', '0003_auto_20201222_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='country',
            new_name='area',
        ),
    ]
